import { getSiteSettings } from "@/lib/site-settings";

export async function generateMetadata() {
  const settings = await getSiteSettings();
  return {
    title: "About",
    description: `Learn about ${settings.siteName}, our mission, and the technology behind our AI-powered content platform.`,
  };
}

export default async function AboutPage() {
  const settings = await getSiteSettings();
  const features = [
    {
      title: "AI-Powered Summaries",
      description:
        "Every article gets an intelligent summary generated by AI, helping readers quickly grasp key insights.",
      icon: "🤖",
    },
    {
      title: "SEO Optimized",
      description:
        "Built-in SEO best practices with structured data, meta tags, and optimized content delivery.",
      icon: "🔍",
    },
    {
      title: "Beautiful Reading Experience",
      description:
        "Clean typography, reading progress indicators, and responsive design for every device.",
      icon: "📖",
    },
    {
      title: "Smart Analytics",
      description:
        "Detailed traffic insights, engagement metrics, and content performance analytics.",
      icon: "📊",
    },
    {
      title: "Newsletter Integration",
      description:
        "Built-in newsletter system to keep your audience engaged and coming back for more.",
      icon: "✉️",
    },
    {
      title: "Dark Mode",
      description:
        "Full dark mode support for comfortable reading in any environment.",
      icon: "🌙",
    },
  ];

  return (
    <div>
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-600 to-purple-700 py-20 text-white">
        <div className="mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8">
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl">
            About {settings.siteName}
          </h1>
          <p className="mt-6 text-xl leading-relaxed text-blue-100">
            We&apos;re building the future of content creation and consumption,
            powered by artificial intelligence.
          </p>
        </div>
      </section>

      {/* Mission */}
      <section className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold tracking-tight">Our Mission</h2>
        <div className="mt-6 space-y-4 text-lg leading-relaxed text-muted-foreground">
          <p>
            At {settings.siteName}, we believe that great content should be
            accessible to everyone. Our platform combines the art of writing with
            the power of artificial intelligence to create a reading experience
            that&apos;s both enriching and efficient.
          </p>
          <p>
            We leverage cutting-edge AI technology to generate intelligent
            summaries, optimize content for search engines, and provide readers
            with personalized content recommendations. Our goal is to make every
            article more discoverable, more engaging, and more impactful.
          </p>
          <p>
            Whether you&apos;re a writer looking to reach a wider audience or a
            reader seeking quality content, {settings.siteName} is designed to
            serve you.
          </p>
        </div>
      </section>

      {/* Features */}
      <section className="bg-muted/50 py-16">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <h2 className="mb-10 text-center text-3xl font-bold tracking-tight">
            What Makes Us Different
          </h2>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="rounded-xl bg-card p-6 shadow-sm transition hover:shadow-md"
              >
                <span className="text-4xl">{feature.icon}</span>
                <h3 className="mt-4 text-xl font-semibold">{feature.title}</h3>
                <p className="mt-2 text-muted-foreground">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Team/Founder */}
      <section className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold tracking-tight">Our Team</h2>
        <div className="mt-8 grid gap-8 sm:grid-cols-2">
          <div className="flex flex-col items-center rounded-xl border bg-card p-8 text-center">
            <div className="flex h-24 w-24 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-purple-500 text-3xl font-bold text-white">
              BF
            </div>
            <h3 className="mt-4 text-xl font-semibold">
              {settings.siteAuthor}
            </h3>
            <p className="text-sm text-muted-foreground">Founder & Lead</p>
            <p className="mt-3 text-sm text-muted-foreground">
              Passionate about AI, web development, and creating tools that
              empower content creators worldwide.
            </p>
          </div>
          <div className="flex flex-col items-center rounded-xl border bg-card p-8 text-center">
            <div className="flex h-24 w-24 items-center justify-center rounded-full bg-gradient-to-br from-green-500 to-teal-500 text-3xl font-bold text-white">
              AI
            </div>
            <h3 className="mt-4 text-xl font-semibold">AI Engine</h3>
            <p className="text-sm text-muted-foreground">
              Content Intelligence
            </p>
            <p className="mt-3 text-sm text-muted-foreground">
              Our AI engine works behind the scenes to summarize content, suggest
              improvements, and optimize for search engines.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
